export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOAD_USER = "LOAD_USER";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const GET_DECKS = "GET_DECKS";
export const GET_DECKS_FAIL = "GET_DECKS_FAIL";
export const CREATE_DECK_FAIL = "CREATE_DECK_FAIL";
export const GET_DECK_FAIL = "GET_DECK_FAIL";
export const DELETE_DECK_FAIL = "DELETE_DECK_FAIL";
export const DELETE_DECK = "DELETE_DECK";
export const GET_DECK_GROUPS = "GET_DECK_GROUPS";
export const GET_DECK_GROUPS_FAIL = "GET_DECK_GROUPS_FAIL";
export const CREATE_DECK_GROUP = "CREATE_DECK_GROUP";
export const CREATE_DECK_GROUP_FAIL = "CREATE_DECK_GROUP_FAIL";
export const DELETE_DECK_GROUP = "DELETE_DECK_GROUP";
export const DELETE_DECK_GROUP_FAIL = "DELETE_DECK_GROUP_FAIL";
export const UPDATE_DECK_GROUP = "UPDATE_DECK_GROUP";
export const UPDATE_DECK_GROUP_FAIL = "UPDATE_DECK_GROUP_FAIL";
